### ISSUE TITLE
Can't login (401 error) on next-gen Jira cloud 

### ISSUE THREAD

**Issue by rdickert** [steyep/alfred-jira#111]
This plugin looks really cool. Thanks for your effort on this! Unfortunately, I haven't figured out how to get started. It could totally be me, but I've tried pretty thoroughly. Salient facts

* using Alfred 4 (seems to work fine - displays login screen and messages)
* On a next-gen cloud-hosted Jira project (using xxxx.atlassian.net url) ([api changes](https://blog.developer.atlassian.com/jira-cloud-next-gen-projects-and-connect-apps/) aren't obviously a problem, but who knows)
* logging in with my email. I've tried to look up if I have a separate user name, but no success - I think in this case my email *is* my username, but maybe I'm wrong? (definitely username/password; Not using oauth).
* The credentials that give me a 401 here successfully log me in on the web. 

Debug output has no useful information. I'm a js coder but haven't figured out how to log more details from the 401 message (if indeed there is anything to learn). 

Any thoughts? If I solve anything, I'll contribute it back to the project, but I don't currently know how to set up dev.

**Comment by mjameswh** [comment]
Just faced the same issue.

This is due to Atlasian's deprecation of basic authentication with passwords, as described [here](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/). What it means is that you can no longer use your username and password as credentials to make request through Jira's REST API.

But don't worry, the solution is simple enough: you just need to create an API token for your account, as described [on this page](https://confluence.atlassian.com/cloud/api-tokens-938839638.html). Then, you login using your username and that token (instead of your password).

James Watkins-Harvey

**Comment by rdickert** [comment]
That worked, thank you @mjameswh!
