### ISSUE TITLE
Enable/Disable Projects & Statuses the user cares about

### ISSUE THREAD

**Issue by damianpoole** [steyep/alfred-jira#14]
The user search uses `'rest/api/2/user/assignable/multiProjectSearch'` this will only return a list of users which have access to every project in the companies Jira instance.

Also returning watched issues/assigned issues uses every status such as "Done" which makes searching for issues potentially difficult.

**Comment by steyep** [comment]
Since not all Jira instances have the same statuses, they are all added to the config file by default. As mentioned in the [README](https://github.com/steyep/alfred-jira/blob/master/README.md), it is recommended that users tweak those settings to only query projects and statuses that are applicable to them:

> After installing the workflow and logging in, an array of all available projects and statuses will be created. It is recommended that you edit this list to give you better results. For example: removing Closed from the list of enabled statuses.
> 
> This can be easily done by selecting Edit Settings from the Settings menu and removing unwanted statuses/projects from the available_projects and available_issues_statuses arrays.
> 
> Clearing the workflow settings and logging in will restore the defaults.

Could that resolve your issue?

**Comment by damianpoole** [comment]
It would however I was more adding the issue as an enhancement (don't think I can label it) request/incoming PR.

**Comment by damianpoole** [comment]
I was thinking along the lines of making it easier for the end user, but who I am kidding. If someone uses Jira and Alfred, they very much should be able to modify an array 😆
