### ISSUE TITLE
Sort Issue by Last Updated

### ISSUE THREAD

**Issue by itainoam** [steyep/alfred-jira#31]
How are issues currently sorted? 
It would nice to sort them by last update date.
For me it seems to correlate well with relevancy.

**Comment by steyep** [comment]
Watched issues *are* sorted by last update date. However, issues that are assigned to you are ordered by priority. This makes more sense (at least to me) because an issue with a higher priority should take precedence over a newer issue with a lower priority. 

That said, I may entertain the idea of adding a "sort by" option to the config so that a user could make that change if they wish.

**Comment by steyep** [comment]
@itainoam, as of `v.1.0.1`, custom sorting has been added to the app. Once you've updated your workflow, you will be able to configure how the issues are returned to you by editing the **Sorting** section of the settings pane. In the screenshot below, issues are returned by `priority` (descending), then `key` (descending). You can add a tertiary sort by pressing the `then` button. Similarly, you can remove a sort definition by pressing the `X` button to the right of the sort you wish to remove. Click the down arrow (descending order) to switch a definition to ascending order.

I hope that gives you the flexibility you were looking for! 😄 

![screen shot 2017-03-06 at 5 24 14 pm](https://cloud.githubusercontent.com/assets/4822034/23636827/c496407e-02a5-11e7-9c5d-3e2faaed9419.png)

**Comment by itainoam** [comment]
Thanks. You are awesome! Looking forward to playing with the new version.
